INSERT INTO USER(USER_ID, USER_NAME, FULL_NAME, EMAIL, CREATION_DATE) VALUES (1, 'admin', 'Administrator', 'admin@gmail.com', CURRENT_TIMESTAMP);
INSERT INTO USER(USER_ID, USER_NAME, FULL_NAME, EMAIL, CREATION_DATE) VALUES (2, 'user1', 'First User', 'yousif.kamal@gmail.com', CURRENT_TIMESTAMP);
INSERT INTO USER(USER_ID, USER_NAME, FULL_NAME, EMAIL, CREATION_DATE) VALUES (3, 'user2', 'Second User', 'yousifkamal@hotmail.com', CURRENT_TIMESTAMP);
INSERT INTO USER(USER_ID, USER_NAME, FULL_NAME, EMAIL, CREATION_DATE) VALUES (4, 'public', 'Public URL Creation User', '', CURRENT_TIMESTAMP);